----RENAME INDEX---
EXEC sp_rename CUSTOMERS_CITY,CUST_CITY

---DISABLE INDEX-----
ALTER INDEX CUSTOMERS_CITY
ON CUSTOMERS DISABLE

SELECT * FROM customers WHERE city='Redondo Beach'

ALTER INDEX CUSTOMERS_CITY
ON CUSTOMERS REBUILD

SELECT * FROM customers WHERE city='Redondo Beach'

----DROP INDEX------
DROP INDEX CUSTOMERS_CITY ON CUSTOMERS

---ENABLE ALL INDEXES OF TABLE---
ALTER INDEX ALL ON CUSTOMERS REBUILD

---DISABLE ALL INDEXES OF TABLE----
ALTER INDEX ALL ON CUSTOMERS DISABLE