----CALL VIEWS-----
SELECT * FROM PRODUCT_INFO
SELECT * FROM PRODUCT_INFO WHERE BRAND_NAME='Trek'
SELECT * FROM PRODUCT_INFO WHERE BRAND_NAME='Trek' ORDER BY LIST_PRICE

SELECT * FROM ORDER_DETAILS_WITH_CUSTOMERS_INFO WHERE CUSTOMER_ID=259

DROP VIEW PRODUCT_INFO

---CALL SYS VIEWS---
SELECT NAME,DATABASE_ID,create_date FROM SYS.DATABASES

SELECT NAME,CREATE_DATE FROM SYS.tables