-- STRING FUNCTIONS --
SELECT ASCII('a') AS 'ASCII FROM CHAR'
SELECT ASCII('A') AS 'ASCII FROM CHAR'
SELECT CHAR(97) AS 'CHAR FROM ASCII'
SELECT CONCAT('WELCOME ', 'TO SQLSERVER') AS 'NEW STRING'
SELECT FIRST_NAME,LAST_NAME,FIRST_NAME+ ' ' +LAST_NAME AS 'FULL NAME' FROM CUSTOMERS
SELECT LEN('DAGDEWR') AS LENGTH
SELECT EMAIL, LEN(EMAIL) AS 'EMAIL LENGTH' FROM CUSTOMERS
SELECT LOWER('FDSAE') AS 'LOWER'
SELECT UPPER('dfsafd') AS 'UPPER'
SELECT LOWER(CITY) AS CITY_UPPER FROM CUSTOMERS
SELECT LTRIM('  FDASF') AS 'LEFT TRIM'
SELECT RTRIM('FDSA ') AS 'RIGHT TRIM'
SELECT REPLACE('THIS IS TEA','TEA','COFFEE') AS RESULT
SELECT CUSTOMER_ID, REPLACE(PHONE, '(916)','(917)') AS NEWPHONE FROM CUSTOMERS
SELECT REVERSE('AXS') AS REVERSED

DECLARE @INPUT VARCHAR(50) = 'REDIVEDER'
SELECT CASE WHEN @INPUT=REVERSE(@INPUT)
THEN  'PALINDROME'
ELSE 'NOT PALINDROME'
END

SELECT FIRST_NAME,LAST_NAME,FIRST_NAME+SPACE(1)+LAST_NAME AS 'FULL NAME' FROM CUSTOMERS

SELECT STR(123,3,0) AS RESULT

SELECT CITY,STRING_AGG(EMAIL,',') AS EMAIL_LIST FROM CUSTOMERS GROUP BY CITY
SELECT STRING_SPLIT('RED,GREEN,BLUE','',') AS NEWVALUES
SELECT SUBSTRING('MS-SQLSERVER',4,9) AS SUBSTRING
SELECT STUFF('SQL TUTORIAL',1,3,'SQL SERVER') AS RESULT