-- SYSTEM FUNCTIONS--
SELECT 1- + cast('10' as int) as result
SELECT CAST(10.45 as INT) SA RESULT
SELECT CAST('01-01-2020' AS DATETIME) AS RESULT
SELECT CONVERT(INT, 10.45) AS RESULT
SELECT CONVERT(DATETIME, '01-01-2020') AS RESULT
SELECT DAT(CAST('01-01-2020' AS DATETIME)) AS RESULT
SELECT CHOOSE(2,'ONE','TWO','THREE') AS RESULT
SELECT ISNULL(NULL,20) AS RESULT
SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME,ISNULL(phone,123) FROM CUSTOMERS
SELECT ISNUMERIC('$432') AS RESULT
SELECT IIF(50<100,'true','false') as result
SELECT CAST('FDAS' AS INT) AS RESULT