----AGGREGATE FUNCTIONS---
SELECT AVG(LIST_PRICE) AS 'AVG PRODUCT PRICE' FROM PRODUCTS
SELECT COUNT(*) AS 'PRODUCT COUNT' FROM PRODUCTS WHERE list_price>300
SELECT MAX(LIST_PRICE) AS 'MAX LIST PRICE' FROM products WHERE LIST_PRICE<1000
SELECT MIN(LIST_PRICE) AS 'MIN LIST PRICE' FROM products
SELECT product_id,SUM(QUANTITY)AS 'TOTAL QTY' FROM stocks GROUP BY PRODUCT_ID
ORDER BY 'TOTAL QTY' DESC