-----CALL UDF-----
SELECT AutomobileDB.dbo.UDFNETSALE(100,10.00) AS 'NET SALES'

SELECT ORDER_ID, SUM(AutomobileDB.dbo.UDFNETSALE(QUANTITY,LIST_PRICE)) NETSALE
FROM ORDER_ITEMS
GROUP BY ORDER_ID ORDER BY NETSALE DESC
