----RETURNING CURRENT DATE---
SELECT GETDATE() AS 'CURRENT DATE'
SELECT CONVERT(DATE,GETDATE())AS 'CURRENT DATE'
SELECT CAST(GETDATE()AS DATE) AS 'CURRENT DATE'
SELECT CAST(GETDATE()AS TIME) AS 'CURRENT TIME'
SELECT SYSDATETIME() AS 'CURRENT DATE'
---RETURNING DATE PART--------
SELECT DATENAME(month,GETDATE()) AS 'DATE PART USING DATENAME'
SELECT DATENAME(month,'08-23-2020') AS 'DATE PART USING DATENAME'
SELECT ORDER_ID,DATENAME(MONTH,ORDER_DATE)AS MONTH FROM ORDERS
SELECT ORDER_ID,DATEPART(YEAR,ORDER_DATE) AS YEAR FROM ORDERS
SELECT ORDER_ID,DAY(ORDER_DATE) AS DAY FROM ORDERS
SELECT ORDER_ID,MONTH(ORDER_DATE) AS MONTH FROM ORDERS
SELECT ORDER_ID,YEAR(ORDER_DATE) AS YEAR FROM ORDERS
SELECT ORDER_ID,CUSTOMER_ID,ORDER_DATE FROM orders WHERE YEAR(shipped_date)=2017
-----DIFF BETWEEN DATES--------
SELECT DATEDIFF(DAY,'01-01-2020','01-01-2021') AS 'DAYS'
SELECT ORDER_ID, DATEDIFF(DAY,ORDER_DATE,SHIPPED_DATE) AS 'DAYS DIFF BETWEEN ORDER DATE AND SHIPPED DATE' FROM ORDERS
SELECT ORDER_ID, DATEDIFF(MINUTE,ORDER_DATE,SHIPPED_DATE) AS 'MINUTES DIFF BETWEEN ORDER DATE AND SHIPPED DATE' FROM ORDERS
SELECT ORDER_ID, DATEDIFF(HOUR,ORDER_DATE,SHIPPED_DATE) AS 'HOURS DIFF BETWEEN ORDER DATE AND SHIPPED DATE' FROM ORDERS
SELECT ORDER_ID, DATEDIFF(SECOND,ORDER_DATE,SHIPPED_DATE) AS 'SECOND DIFF BETWEEN ORDER DATE AND SHIPPED DATE' FROM ORDERS
SELECT ORDER_ID, DATEDIFF(MILLISECOND,ORDER_DATE,SHIPPED_DATE) AS 'MILLI SEC DIFF BETWEEN ORDER DATE AND SHIPPED DATE' FROM ORDERS
SELECT ORDER_ID, DATEDIFF(MICROSECOND,ORDER_DATE,SHIPPED_DATE) AS 'MICRO SEC DIFF BETWEEN ORDER DATE AND SHIPPED DATE' FROM ORDERS
---MODIFYING DATE------
SELECT DATEADD(DAY,10,GETDATE()) AS 'NEW DATE'
SELECT DATEADD(MONTH,1,GETDATE()) AS 'NEW DATE'
SELECT DATEADD(YEAR,1,GETDATE()) AS 'NEW DATE'
SELECT ORDER_ID, DATEADD(DAY,5,order_date) AS 'EST SHIPP DATE' FROM orders
----VALIDATE DATE-----
SELECT ISDATE('01-01-2017') AS 'IS DATE'
SELECT ISDATE('DFDFD') AS 'IS DATE'