---STRING FUNCTIONS---
SELECT ASCII('a') AS 'ASCII FROM CHAR'
SELECT ASCII('A') AS 'ASCII FROM CHAR'
SELECT CHAR(97) AS  'CHAR FROM ASCII'
SELECT CONCAT('WELCOME ','TO SQLSERVER') AS 'NEW STRING'
SELECT 'WELCOME'+' TO SQLSERVER' AS MESSAGE 
SELECT FIRST_NAME,LAST_NAME,FIRST_NAME+ ' '+LAST_NAME AS 'FULL NAME' FROM CUSTOMERS
SELECT LEN('DSGDSGDSDSGDSG') AS LENGTH
SELECT EMAIL, LEN(EMAIL) AS 'EMAIL LENGTH' FROM CUSTOMERS
SELECT LOWER('GDGGDFGDFG') AS 'LOWER'
SELECT UPPER('dfdfdfd') as 'UPPER'
SELECT UPPER(CITY) AS CITY FROM CUSTOMERS
SELECT LOWER(CITY) AS CITY FROM CUSTOMERS
SELECT LTRIM(' DSGFGDGGGDFG') AS 'LTRIM'
SELECT RTRIM('DSFDSFDFDS ') AS 'RTRIM'
SELECT REPLACE('its a good tea at the famous tea store','tea','coffee') as result
SELECT CUSTOMER_ID, REPLACE(PHONE,'(916)','(917)')AS NEWPHONE  FROM customers
SELECT REPLICATE('HELLO',3) AS REPLICATED
SELECT REVERSE('ZYZ') AS REVERSED

DECLARE @INPUT VARCHAR(50)='REDIVIDER'
SELECT CASE WHEN @INPUT=REVERSE(@INPUT)
THEN 'PALINDROME'
ELSE 'NOT PALINDROME'
END 

SELECT FIRST_NAME,LAST_NAME,FIRST_NAME + SPACE(1) +LAST_NAME AS 'FULL NAME' FROM CUSTOMERS

SELECT STR(123,3,0) AS RESULT

SELECT CITY,STRING_AGG(email,',') AS EMAIL_LIST FROM customers GROUP BY CITY

SELECT STRING_SPLIT('RED,GREEN,BLUE',',') AS NEWVALUES

SELECT SUBSTRING('MS-SQLSERVER',4,9) AS SUBSTRING

SELECT STUFF('SQL TUTORIAL',1,3,'SQL SERVER') AS RESULT