-----SYSTEM FUNCTIONS-----
SELECT 10 + CAST('10' AS INT) AS RESULT
SELECT CAST(10.70 AS INT) AS RESULT
SELECT DAY( CAST('01-01-2020' AS DATETIME)) AS RESULT
SELECT CONVERT(INT,10.45) AS RESULT
SELECT CONVERT(DATETIME,'01-01-2020') AS RESULT
SELECT CHOOSE(2,'ONE','TWO','THREE') AS RESULT
SELECT ISNULL(NULL,20) AS RESULT

SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME, ISNULL(phone,123) FROM customers WHERE PHONE IS NULL
SELECT ISNUMERIC('$3435') AS RESULT
SELECT IIF(50<100,'TRUE','FALSE') AS RESULT

SELECT CAST('fdfsdf' AS INT) AS RESULT
SELECT TRY_CAST('DFDSF' AS INT) AS RESULT
SELECT TRY_CONVERT(ÍNT,'DSFDSF') AS RESULT
