----WINDOW FUNCTIONS----
SELECT  PRODUCT_ID,PRODUCT_NAME,LIST_PRICE, RANK() 
OVER(ORDER BY LIST_PRICE DESC) AS 'PRICE RANK' 
FROM products

SELECT ROW_NUMBER() OVER (ORDER BY FIRST_NAME) AS 'ROW NO',
first_name, LAST_NAME,CITY FROM CUSTOMERS

SELECT FIRST_NAME,LAST_NAME,CITY,ROW_NUMBER() 
OVER (
	PARTITION BY CITY ORDER BY FIRST_NAME
) AS 'ROW NO'
FROM CUSTOMERS ORDER BY CITY