----CALL SIMPLE STORED PROCEDURES---
EXEC USPPRODUCTLIST
----CALL PARAMETERIZED STORED PROCEDURE---
EXEC USPFINDPRODUCTS 2
EXEC USPFINDPRODUCTS @PRODUCT_ID=2

EXEC USPADDPRODUCTS @product_name='ABC',@brand_id=1,@category_id=1,@model_year=2020,@list_price=120
SELECT * FROM products WHERE product_name='ABC'
----CALL STORED PROCEDURE WITH OPTIONAL PARAMETER---
EXEC uspFindProductByListPrice @NAME='Trek'
----CALL STORED PROCEDURE WITH OUTPUT PARAMETER
DECLARE @COUNT INT
EXEC uspFindProductByModel @MODEL_YEAR=2017,
@PRODUCT_COUNT=@COUNT OUTPUT
SELECT @COUNT AS 'NUMBER OF PRODUCTS'

---CALL STORED PROCEDURE WITH MSG----
EXEC SELECT_PRODUCT_BY_LIST_PRICE

---CALL VARIABLE STORED PROCEDURE--- 
EXEC FIND_MOST_EXPENSIVE_PRODUCT

---PROCEDURE WITH TRY CATCH--
DECLARE @R DECIMAL
EXEC USP_DIVIDE 10,0, @R OUTPUT
PRINT @R