---STORED PROCEDURE WITH OUTPUT PARAMETER---
CREATE PROCEDURE uspFindProductByModel(
@MODEL_YEAR SMALLINT,
@PRODUCT_COUNT INT OUTPUT
)
AS
BEGIN
SELECT * FROM products WHERE model_year=@MODEL_YEAR
SELECT @PRODUCT_COUNT= @@ROWCOUNT
--RETURN @@ROWCOUNT
END