----EXCEPTION HANDLING---
CREATE PROCEDURE USP_DIVIDE(
@A DECIMAL,
@B DECIMAL,
@C DECIMAL OUTPUT
)
AS
 BEGIN
	BEGIN TRY
		SET @C=@A/@B;
	END TRY
	BEGIN CATCH
		SELECT
		ERROR_NUMBER() AS 'ERROR NUMBER',
		ERROR_SEVERITY() AS 'ERROR SEVERITY',
		ERROR_STATE() AS 'EROR STATE',
		ERROR_LINE() AS 'ERROR LINE',
		ERROR_MESSAGE() AS 'ERROR MESSAGE'
	END CATCH
 END 