----GROUP BY-----
SELECT CUSTOMER_ID,COUNT(order_id)AS 'NO.OF ORDERS' FROM orders WHERE customer_id IN(2,3)GROUP BY CUSTOMER_ID
SELECT CUSTOMER_ID,COUNT(ORDER_ID) AS 'NO. OF ORDERS' FROM orders GROUP BY customer_id


SELECT CITY,COUNT(CUSTOMER_ID) AS COUNT FROM customers GROUP BY CITY
SELECT CITY,COUNT(CUSTOMER_ID) AS COUNT FROM customers GROUP BY city ORDER BY CITY

SELECT ORDER_ID,SUM(QUANTITY*LIST_PRICE) AS 'TOTAL' FROM order_items GROUP BY ORDER_ID 

SELECT STAFF_ID,COUNT(order_id)AS 'ORDER COUNT' FROM ORDERS GROUP BY STAFF_ID

SELECT PRODUCT_ID,SUM(QUANTITY) AS 'QTY' FROM stocks GROUP BY product_id

SELECT state,COUNT(customer_id) FROM CUSTOMERS GROUP BY STATE
-----HAVING------------------
SELECT customer_id,YEAR(order_date)AS 'YEAR',COUNT(order_id) AS 'ORDER COUNT' FROM ORDERS GROUP BY CUSTOMER_ID,YEAR(order_date) HAVING COUNT(ORDER_ID)>=2

SELECT order_id,SUM(quantity*list_price) AS 'TOTAL' FROM ORDER_ITEMS GROUP BY ORDER_ID HAVING SUM(quantity*list_price)>=2000 ORDER BY TOTAL DESC

SELECT product_id,SUM(QUANTITY) AS 'QTY' FROM stocks GROUP BY PRODUCT_ID HAVING SUM(quantity)>50 ORDER BY QTY DESC

SELECT STAFF_ID,COUNT(order_id) AS 'ORDER COUNT' FROM ORDERS GROUP BY staff_id HAVING COUNT(order_id)>50 ORDER BY 'ORDER COUNT' DESC
