CREATE TABLE CANDIDATES(
id int IDENTITY PRIMARY KEY,
fullname VARCHAR(100) NOT NULL
);

CREATE TABLE EMPLOYEES(
id int IDENTITY PRIMARY KEY,
fullname VARCHAR(100) NOT NULL
);

INSERT INTO 
candidates(fullname)
VALUES
('John Doe'),
('Lily Bush'),
('Peter Drucker'),
('Jane Doe');

INSERT INTO 
employees(fullname)
VALUES
('John Doe'),
('Jane Doe'),
('Michael Scott'),
('Jack Sparrow');

----INNER JOIN----
SELECT C.id,C.fullname,E.id FROM CANDIDATES C INNER JOIN EMPLOYEES E ON C.fullname =E.fullname
SELECT C.FIRST_NAME,C.LAST_NAME,C.EMAIL,O.ORDER_ID,O.ORDER_STATUS,O.ORDER_DATE FROM CUSTOMERS C INNER JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID


---RIGHT JOIN (RIGHT OUTER JOIN)-----
SELECT * FROM CANDIDATES C RIGHT JOIN EMPLOYEES E ON C.fullname=E.fullname


----LEFT JOIN (LEFT OUTER JOIN)-----
SELECT * FROM CANDIDATES C LEFT JOIN EMPLOYEES E ON C.fullname=E.fullname
DELETE FROM ORDERS WHERE CUSTOMER_ID=1
SELECT C.CUSTOMER_ID, C.FIRST_NAME,C.LAST_NAME,O.CUSTOMER_ID,O.ORDER_STATUS,ORDER_DATE FROM CUSTOMERS C LEFT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID

----FULL JOIN (FULL OUTER JOIN)---------
SELECT * FROM CANDIDATES C FULL JOIN EMPLOYEES E ON C.fullname=E.fullname

SELECT C.CUSTOMER_ID,C.FIRST_NAME,C.EMAIL,O.ORDER_ID,O.ORDER_DATE,I.ORDER_ID,I.ITEM_ID,I.QUANTITY,I.LIST_PRICE FROM CUSTOMERS C 
INNER JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
INNER JOIN ORDER_ITEMS I ON O.ORDER_ID=I.ORDER_ID



