---SELECT STATEMENT---
SELECT * FROM CUSTOMERS
SELECT CUSTOMER_ID AS ID,FIRST_NAME AS FIRSTNAME,LAST_NAME AS LASTNAME,(FIRST_NAME +' ' + LAST_NAME)AS NAME,EMAIL,CITY,STATE FROM CUSTOMERS

---ORDER BY-----------
SELECT * FROM CUSTOMERS ORDER BY EMAIL 
SELECT * FROM CUSTOMERS ORDER BY EMAIL DESC
SELECT CITY,FIRST_NAME,LAST_NAME FROM CUSTOMERS ORDER BY CITY,FIRST_NAME
SELECT CITY,FIRST_NAME,LAST_NAME FROM CUSTOMERS ORDER BY CITY DESC,FIRST_NAME ASC
SELECT FIRST_NAME,LAST_NAME FROM CUSTOMERS ORDER BY LEN(FIRST_NAME) 
SELECT FIRST_NAME,LAST_NAME FROM CUSTOMERS ORDER BY LEN(FIRST_NAME) DESC 

----SELECT TOP-------
SELECT TOP 10 * FROM PRODUCTS
SELECT TOP 10 PRODUCT_ID,PRODUCT_NAME,MODEL_YEAR,LIST_PRICE FROM PRODUCTS
SELECT TOP 10 * FROM PRODUCTS ORDER BY LIST_PRICE DESC
SELECT TOP 10 PERCENT * FROM PRODUCTS
SELECT TOP 10 PERCENT * FROM PRODUCTS ORDER BY LIST_PRICE DESC
---DISTINCT----------
SELECT DISTINCT CITY FROM CUSTOMERS ORDER BY CITY
SELECT DISTINCT CITY,STATE FROM CUSTOMERS
----WHERE------------
SELECT * FROM PRODUCTS WHERE CATEGORY_ID=3 ORDER BY LIST_PRICE
SELECT * FROM PRODUCTS WHERE CATEGORY_ID=1 AND MODEL_YEAR=2018
SELECT * FROM PRODUCTS WHERE LIST_PRICE>200
-----AND-------------------
SELECT * FROM PRODUCTS WHERE CATEGORY_ID <>1 AND CATEGORY_ID <>2
-----OR---------------------
SELECT * FROM PRODUCTS WHERE MODEL_YEAR=2018 OR MODEL_YEAR=2019
----BTWEEN AND--------------
SELECT * FROM PRODUCTS WHERE LIST_PRICE BETWEEN 1500 AND 1900 ORDER BY LIST_PRICE
SELECT * FROM ORDERS WHERE ORDER_DATE BETWEEN '2016-01-01' AND '2018-01-01' ORDER BY ORDER_DATE
----IN--------------------
SELECT * FROM PRODUCTS WHERE LIST_PRICE=269.99 OR LIST_PRICE=449.00 OR LIST_PRICE=999.99 ORDER BY LIST_PRICE  
SELECT * FROM PRODUCTS WHERE LIST_PRICE IN(269.99,449.0,999.99)ORDER BY LIST_PRICE
SELECT * FROM PRODUCTS WHERE MODEL_YEAR IN(2017,2019) ORDER BY MODEL_YEAR
SELECT * FROM CUSTOMERS WHERE STATE IN('NY','CA') ORDER BY STATE
------IS NULL----------
SELECT * FROM CUSTOMERS WHERE PHONE IS NULL ORDER BY CUSTOMER_ID
---IS NOT NULL---------
SELECT * FROM CUSTOMERS WHERE PHONE IS NOT NULL ORDER BY CUSTOMER_ID
---LIKE---------------
SELECT * FROM CUSTOMERS WHERE LAST_NAME LIKE 'Z%' ORDER BY FIRST_NAME
SELECT * FROM CUSTOMERS WHERE LAST_NAME LIKE '%ER'ORDER BY FIRST_NAME
SELECT * FROM CUSTOMERS WHERE LAST_NAME LIKE 'T%S'ORDER BY FIRST_NAME 
SELECT * FROM CUSTOMERS WHERE LAST_NAME LIKE '_U%' ORDER BY FIRST_NAME
SELECT * FROM CUSTOMERS WHERE LAST_NAME LIKE '[YZ]%' ORDER BY FIRST_NAME
----NOT LIKE----------
SELECT * FROM CUSTOMERS WHERE LAST_NAME NOT LIKE 'A%' ORDER BY FIRST_NAME
SELECT * FROM CUSTOMERS WHERE LAST_NAME NOT LIKE '%ER'ORDER BY FIRST_NAME
SELECT * FROM CUSTOMERS WHERE LAST_NAME NOT LIKE 'T%S'ORDER BY FIRST_NAME 
SELECT * FROM CUSTOMERS WHERE LAST_NAME NOT LIKE '_U%' ORDER BY FIRST_NAME
SELECT * FROM CUSTOMERS WHERE LAST_NAME NOT LIKE '[YZ]%' ORDER BY FIRST_NAME