---SET OPERATORS----
SELECT staff_id, FIRST_NAME,LAST_NAME FROM staffs
UNION
SELECT customer_id, FIRST_NAME,LAST_NAME FROM CUSTOMERS

SELECT STAFF_ID,FIRST_NAME,LAST_NAME FROM staffs
UNION ALL
SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME FROM customers

SELECT * FROM CANDIDATES 
UNION
SELECT * FROM EMPLOYEES

SELECT * FROM CANDIDATES 
UNION ALL
SELECT * FROM EMPLOYEES ORDER BY FULLNAME

SELECT * FROM CANDIDATES
INTERSECT
SELECT * FROM EMPLOYEES

SELECT CITY FROM customers
INTERSECT
SELECT CITY FROM stores ORDER BY CITY

SELECT PRODUCT_ID FROM products 
EXCEPT
SELECT PRODUCT_ID FROM ORDER_ITEMS