----SUB QUERY---
SELECT * FROM orders WHERE customer_id IN(
SELECT CUSTOMER_ID FROM customers WHERE city='NEW YORK') ORDER BY order_date

SELECT PRODUCT_NAME,LIST_PRICE FROM products WHERE list_price>=ALL(
SELECT AVG(LIST_PRICE) FROM products) 

SELECT CUSTOMER_ID,first_name,last_name,CITY FROM customers C WHERE EXISTS(
SELECT CUSTOMER_ID FROM orders O WHERE O.customer_id=C.CUSTOMER_ID AND YEAR(ORDER_DATE)=2017)